### ISSUE TITLE
Gulp/Duplexify issue

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/riskmap#275]
Looks like there's a bug in a Gulp dependency which is causing builds to fail, which seems to coincide with the latest release of Gulp (this week).

Recommended action is to not make changes to package-lock.json (or stash them) before committing.

Error message is below and here's the diff between working and broken versions: https://github.com/urbanriskmap/riskmap/commit/cafaba9d577f87a6c2794333130def9d8489f364#diff-32607347f8126e6534ebc7ebaec4853dR4598

```
{ uid: 3,
  name: 'processLocales',
  branch: false,
  error: 
   Error: premature close
       at Pumpify.onclose (/var/lib/jenkins/workspace/petabencana.id-dev/node_modules/end-of-stream/index.js:43:67)
       at emitNone (events.js:105:13)
       at Pumpify.emit (events.js:207:7)
       at Pumpify.Duplexify._destroy (/var/lib/jenkins/workspace/petabencana.id-dev/node_modules/duplexify/index.js:192:8)
       at /var/lib/jenkins/workspace/petabencana.id-dev/node_modules/duplexify/index.js:175:10
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickDomainCallback (internal/process/next_tick.js:218:9),
  duration: [ 0, 7104716 ],
  time: 1515171343785 }
```

**Comment by talltom** [comment]
cc. @asbarve @ojha-url @matthewberryman

**Comment by talltom** [comment]
Here's another project with the same issue: https://github.com/versatica/mediasoup-demo/issues/15

**Comment by talltom** [comment]
NPM versions locked down in 999220d07908885593f02405a338e57029738031.

I can now build.
